### ISSUE TITLE
calling `conda` on windows

### ISSUE THREAD

**Issue by keewis** [mamba-org/provision-with-micromamba#104]
I've been using `conda info -a` after setting up the environment with this action, which will provide a bit more information than the `micromamba info` that is called by the action. In particular, I'm interested in the information from `conda info -s`.

However, when upgrading the action from `0.12` to `0.13` (or `0.14`) this starts failing on windows with `conda: command not found`. It seems that `conda` is installed on linux / macos by default, but on windows the install needs to be explicit. While it is certainly true that relying on implicit installs is bad style (so I switched to explicit), I wonder if this inconsistency is intentional?

---

I suppose another way to fix this would be to support something like `micromamba info -a` and call that from the action, but I guess that's a feature request for `micromamba`?

**Comment by jonashaag** [comment]
I don‘t think this is related to this action but to the runner image you are using. Maybe GH updated their default windows image.

**Comment by keewis** [comment]
that could be. Do you have any suggestion on how to figure that out? If it helps, here's a minimal [workflow run](https://github.com/keewis/test-project/actions/runs/3365238177).

However, if you don't think that this matters too much feel free to close: as I mentioned, explicitly installing `conda` fixes this for me.

**Comment by jonashaag** [comment]
Yeah, I'm going to close this. We could implement `micromamba info -s`.
