### ISSUE TITLE
lock files must end with `.lock`?

### ISSUE THREAD

**Issue by klieret** [mamba-org/provision-with-micromamba#106]
It took me a while to realize that the package refuses to deal with `conda-lock` files if they have a `yaml` ending (throwing a very ugly decoding error). Could this be made clearer in the documentation? Or perhaps even with an additional explicit check (or caught/reraised exception) for a better warning message?

**Comment by jonashaag** [comment]
I agree, there other similar implicit rules/assumptions as well

**Comment by jonashaag** [comment]
Please recreate this issue with https://github.com/mamba-org/setup-micromamba if it is still relevant.
