### ISSUE TITLE
Figure out if we can cache `pkgs` folder

### ISSUE THREAD

**Issue by wolfv** [mamba-org/provision-with-micromamba#11]
Github Actions supports caching (up to 5 Gb).

We could cache pkgs so that they don't have to be re-downloaded and unpacked every time. That could give another decent speed boost.

**Comment by wolfv** [comment]
micromamba now has a `micromamba clean` command that removes un-used packages.

Could be useful for this

**Comment by wolfv** [comment]
Additionally it would be really cool to have automatic `ccache` caching when using the micromamba action

**Comment by wolfv** [comment]
This is how the cache stuff from @actions can be used from JS:

https://github.com/actions/toolkit/tree/main/packages/cache#usage

**Comment by maartenbreddels** [comment]
In my experience the caching and restoring for large environments was slower than building the environment, i suspected this was due to compression and/or decompression. Are the unzipped downloads stored somewhere?

**Comment by wolfv** [comment]
In the `pkgs` folder you have the cached tarballs and extracted directories.

We could remove tarballs with `micromamba clean -t` and then only cache the extracted directories

**Comment by wolfv** [comment]
yeah that's a bit different from my suggestion but may also work well ... 
Well, it's just zipping quite a few files, depending on the env size, so it's kinda expected to take some time to cache/and un-cache :)

**Comment by jonashaag** [comment]
I've spent some time optimizing env/pkg cache for some repos recently. Observations:

- Having a pkg cache is always faster than not having one.
- On Windows, having an env cache is MUCH faster than having a pkg cache.

Nowadays the cache action uses zstd so decompression should be really fast.

**Comment by jonashaag** [comment]
By the way we could also cache the micromamba download, although it that would be more of a traffic reduction technique than a speedup because the download is really fast.
