### ISSUE TITLE
`setup-micromamba` rewrite specification

### ISSUE THREAD

**Issue by jonashaag** [mamba-org/provision-with-micromamba#114]
We're going to release a new version of `provision-with-micromamba`:

- With a new name, `setup-micromamba` (other suggestions welcome; the action's main task is to set up a Conda environment using Micromamba)
- Rewritten in TypeScript
- Using semantic versioning

We will add a upgrade hint to this repo and maybe add a warning in the GHA output.

## Use cases

We'll remove some of the options of provision-with-micromamba, see here for discussion https://github.com/mamba-org/provision-with-micromamba/issues/103.

Here we'll collect some use cases that we want to support. Feel free to make more suggestions.

### Env from `environment.yml`

Options:

- Path to `environment.yml` (no implicit default of `./environment.yml` like in  provision-with-micromamba)
- Optional path to `.condarc` (implicit default to `~/.condarc`)

### Env from `environment.yml` with extra specs

Like above, but with an optional `extra-specs: x y z` option. This is runs

```
micromamba create -f environment.yml x y z
```

### Env without `environment.yml`

For tiny CI setups, options:

- Extra specs
- `environment-name` to substitute the missing `name:` in `environment.yml`
- Channels from `.condarc`

### Installing Micromamba only

- Provide `create-env: false` to skip `micromamba create` and just download + setup Micromamba.

### Creating an empty env

Not sure if we should support this.

### Implicit conda-forge

If using only extra specs and no `.condarc` is given, default to `conda-forge`? Although this reuqires that we check `.condarc`.

### `.condarc` as string

Allow syntax like the following?

```
with:
  condarc: |
    channels:
      - x
```

Although this is also possible simply by using `cat` in a preceding step.

## Proposal

Derived from the use cases, we offer the following options:

- `condarc-file`: Path to a `.condarc` file to consider, defaults to `~/.condarc`.
- `environment-file`: Path to environment file, no default.
- `environment-name`: Override `name:` in `environment.yml` and set name if not passing `environment.yml`.
- `extra-specs`: String with extra specs to pass to `micromamba create`.
- `create-args`: List of strings that are passed to `micromamba create`.
- `create-env: false` to skip `micromamba create`.
- `micromamba-version`, `cache-*`, `log-level`, `installer-url`, `post-deinit`.

**Comment by pavelzw** [comment]
What will happen when you don't supply anything to `environment-file`?
Will an env still be created? What will the name be? `base`?

I think it makes sense to allow the user *just* to install micromamba without any environment creation steps, maybe by setting `create-env: false`. One fictional use case would be that the user wants to make sure that a certain package is pushed to a repository and just wants to do `micromamba search <package>`. This doesn't need an environment.

**Comment by pavelzw** [comment]
Some thoughts on `log-level`: GitHub Actions support different log-levels natively. See [Workflow commands for GitHub Actions / Setting a debug message](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-a-debug-message). 

The debug mode is active when `ACTIONS_SETUP_DEBUG=true`. You can print debug messages by executing `echo "::debug::This is a debug message"`. These messages only get printed (in purple) when `ACTIONS_SETUP_DEBUG=true`. This can be achieved by setting it in the workflow itself or by enabling debug logging when [rerunning a workflow](https://docs.github.com/en/actions/managing-workflow-runs/re-running-workflows-and-jobs#re-running-all-the-jobs-in-a-workflow).

Since we probably cannot add `::debug::` in between micromamba logs, I think it would be a good idea to set the log-level to debug when `ACTIONS_SETUP_DEBUG=true` automatically. Then you do not need to create a separate commit to do this when encountering an error.

See [here](https://github.com/pavelzw/ci-test/actions/runs/3940368545/attempts/1) for an example with debug turned off and [here](https://github.com/pavelzw/ci-test/actions/runs/3940368545) for an example with debug logging.

**Comment by pavelzw** [comment]
Also, we should use dependabot to upgrade the version of `@actions/core`. I see far too many actions that still use old versions of this package resulting in node deprecation warnings as well as `set-output` deprecation warnings.

**Comment by jonashaag** [comment]
OK added it!

**Comment by pavelzw** [comment]
I think adding some sort of environment information, i.e. which exact package versions were installed, to the step output (maybe even optional to the job summary?) might also be helpful.

**Comment by jonashaag** [comment]
It’s already there in the „Environment Info“ output, or are you looking for something else?

**Comment by pavelzw** [comment]
I meant the `GITHUB_OUTPUT` for a specific step such that you can you can use this output in future Workflow steps, see [here](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter).

**Comment by pavelzw** [comment]
Maybe adding something like `init-shell: ['zsh', 'bash']` would also be a nice option to make it easier to manage stateful selfhosted runners.

**Comment by pavelzw** [comment]
If it is possible to add `micromamba` as a shell option in GitHub (see [ADR 0277](https://github.com/actions/runner/blob/main/docs/adrs/0277-run-action-shell-options.md)), we should explore this option. Having something like

```yml
- run: pytest ...
  shell: micromamba
```

would be a nice to have.

**Comment by zacharyburnett** [comment]
This would be great for me, as I have recently had issues running `provision-with-micromamba` on a self-hosted runner, as it overwrites and adds to the `.condarc` file every time.

**Comment by jonashaag** [comment]
> This would be great for me, as I have recently had issues running `provision-with-micromamba` on a self-hosted runner, as it overwrites and adds to the `.condarc` file every time.

Note this: https://github.com/mamba-org/provision-with-micromamba#post-deinit

**Comment by mikemhenry** [comment]
This proposal looks great, I use this action extensively (I've been switching to this action from the mamba/conda ones whenever I get the chance) and the proposal covers all of my use cases.

**Comment by pavelzw** [comment]
The first release of [`setup-micromamba`](https://github.com/mamba-org/setup-micromamba) is out, feel free to check it out 🎉
