### ISSUE TITLE
Display solver error better

### ISSUE THREAD

**Issue by wolfv** [mamba-org/provision-with-micromamba#115]
Currently solver errors are masked by a JS error, e.g.:

<img width="1529" alt="Screenshot 2023-01-19 at 12 52 29" src="https://user-images.githubusercontent.com/885054/213435609-6de338c9-4f80-4763-b654-9cef41b342ca.png">

**Comment by jonashaag** [comment]
How are we doing with setup-micromamba here @pavelzw?

**Comment by pavelzw** [comment]
I haven't given error messages much thought yet. Currently, solver errors look like this in `setup-micromamba`

![image](https://user-images.githubusercontent.com/29506042/235612983-0818cf1c-4b18-4a82-b8a6-cd6052461af8.png)
