### ISSUE TITLE
Cache Question

### ISSUE THREAD

**Issue by mikemhenry** [mamba-org/provision-with-micromamba#120]
If I have `cache-downloads` and `cache-env` both true, does that mean if there is a cache miss for the `env`, the download cache will be used when packages are being downloaded?

**Comment by jonashaag** [comment]
Yes!

**Comment by mikemhenry** [comment]
Awesome! I've been using this action everywhere I can and I've seen some great speedups in my CI, and which these cache options we are zooming!
