### ISSUE TITLE
caching: upload directly after installing the environment

### ISSUE THREAD

**Issue by tdegeus** [mamba-org/provision-with-micromamba#44]
The caching feature is amazing.
There is a situation where it is however not helping me as much as I think it can.
Suppose that I'm investigating some mysterious error in which code hangs. In this case the environment was installed correctly, but it was not yet uploaded. This is a pity because especially solving such a mysterious bug involves many CI runs.

(This might be a restriction of GH Actions, but still, I think it's worth reporting)

**Comment by wolfv** [comment]
I think what we rather want is to _always_ run the post action (even if some other step along the way failed).

It looks like we could use something like `post-if: always()`

https://github.com/actions/runner/issues/987

**Comment by wolfv** [comment]
Look here: https://github.com/mamba-org/provision-with-micromamba/blob/5fe88d370c741fc3567126d17c5af0b9620bd60d/action.yml#L65

cc @jonashaag what do you think? We could check inside the `post.js` file if the environment was properly created and "manually" skip the uploading if micromamba failed?

**Comment by wolfv** [comment]
maybe there is also a way to check for success of the environment creation step ...

**Comment by jonashaag** [comment]
You mean of the entire `use: provision-with-micromamba` step? That sounds like a good idea.
