### ISSUE TITLE
Does not recognize unified lock file.

### ISSUE THREAD

**Issue by chaichontat** [mamba-org/provision-with-micromamba#47]
`conda-lock` [v1.0](https://github.com/conda-incubator/conda-lock/releases/tag/v1.0.0) included a new unified lock file format. However, this actions does not recognize that file format yet.

**Comment by wolfv** [comment]
@chaichontat we are currently working on this in https://github.com/mamba-org/mamba/pull/1577

Feel free to let us know additional thoughts over there.
