### ISSUE TITLE
Should environment-name set and environment-file not set create an environment?

### ISSUE THREAD

**Issue by ossareh** [mamba-org/provision-with-micromamba#52]
Hey there, 

I'll happily provide a patch for this, but before doing that I wanted to check whether I'm missing some technical reason for this not working.

Context: we use tox to run tests, and tox-conda to setup our conda env in the tox virtualenv. I want to use `provision-with-micromamba` to speed up the solve stage of our conda environment creation inside our tox virtualenv.

Variables:
 - environment-name is set to 'myenv'
 - environment-file is set to 'false'
 - extra-specs is set to `tox`

Current flow:
 - [`let envName` defaults to `undefined`](https://github.com/mamba-org/provision-with-micromamba/blob/main/index.js#L221)
 - [envName is never set due to this check](https://github.com/mamba-org/provision-with-micromamba/blob/main/index.js#L225)
 - [named environment is never created](https://github.com/mamba-org/provision-with-micromamba/blob/main/index.js#L263)

It seems the simple fix would be to change the `let envName` to something like:

```javascript
let envFilePath, envName = inputs.envName
```

This would allow the tool to create environments with just the `extra-specs` that are provided.

Am I missing some reason this would not be desirable?

**Comment by jonashaag** [comment]
Can you check if the problem remains in https://github.com/mamba-org/provision-with-micromamba/pull/45?

**Comment by jonashaag** [comment]
I think this should be fixed
