### ISSUE TITLE
Micromamba certificate expired

### ISSUE THREAD

**Issue by kwohlfahrt** [mamba-org/provision-with-micromamba#57]
The action fails to download micromamba, with the error below:

```
  /usr/bin/bash -c curl https://micro.mamba.pm/api/micromamba/linux-64/latest -Ls --retry 5 --retry-delay 1     | tar --strip-components=1 -vxjC /home/runner/micromamba-bin bin/micromamba
  
  bzip2: Compressed file ends unexpectedly;
  	perhaps it is corrupted?  *Possible* reason follows.
  bzip2: Inappropriate ioctl for device
  	Input file = (stdin), output file = (stdout)
```

Testing it at the command line shows a certificate issue at this URL:

```
> curl https://micro.mamba.pm/api/micromamba/linux-64/latest
curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.se/docs/sslcerts.html
```

It seems [upstream](https://github.com/mamba-org/mamba#micromamba) recommends a different source URL: `https://micromamba.snakepit.net/api/micromamba/linux-64/latest`. This one has no cert issues at the moment, is there a reason we aren't using this one?

**Comment by wolfv** [comment]
Hi @kwohlfahrt the `micro.mamba.pm` is the recommended domain. Unfortunately the certificate expired on a Sunday :/ we'll be fixing it first thing tomorrow morning and add in additional safeguards. Sorry for this disruption :/

**Comment by wolfv** [comment]
this is fixed now and we have some better monitoring. Sorry again.

**Comment by kwohlfahrt** [comment]
Thanks for the quick fix!
