### ISSUE TITLE
micromamba is downloaded into working dir

### ISSUE THREAD

**Issue by wolfv** [mamba-org/provision-with-micromamba#7]
There is a conflict if a `micromamba` directory is in the git repository, as tar doesn't want to override that file.
I think we should download micromamba to some temporary directory.

**Comment by beckermr** [comment]
Thanks @wolfv! This should be an easy fix.

**Comment by wolfv** [comment]
I think we should use `runner.temp` as the directory to download micromamba initially to. but then idk where to put the micromamba file ...

**Comment by beckermr** [comment]
On linux/osx, we can create a hidden dir in the home area. IDK how this works on windows.
