### ISSUE TITLE
Make it work on `linux-aarch64` (and `osx-arm64`)

### ISSUE THREAD

**Issue by wolfv** [mamba-org/provision-with-micromamba#70]
We currently hard-code `-64` here: https://github.com/mamba-org/provision-with-micromamba/blob/34071ca7df4983ccd272ed0d3625818b27b70dcc/index.js#L244

Would be great to check for the CPU architecture and use `-aarch64` or `-arm64` when appropriate.

**Comment by nerohmot** [comment]
I have an Linux/aarch64 machine (Ubuntu 22.04) with a self hosted runner on it.
In my action I tried to use `provision-with-micromamba`, but I got the following error:
![image](https://user-images.githubusercontent.com/3516972/175918793-7faf487a-09f9-4b1d-a0f1-d48dff163b21.png)

**Comment by jonashaag** [comment]
Can we test this on GHA?

**Comment by jonashaag** [comment]
Linux x64

```
> require("process").arch
'x64'
```

macOS ARM

```
> require("process").arch
'arm64'
```
