### ISSUE TITLE
setting  channel-priority does not work

### ISSUE THREAD

**Issue by vrecan** [mamba-org/provision-with-micromamba#87]
When setting channel priority to flexible or disabled it still adds it to the command line arguments which overrides the rc file.

Plugin specification:
```
      - uses: mamba-org/provision-with-micromamba@v12
        with:
          channel-priority: flexible
          environment-file: projects/data_integrity/environment.yml
```
```
/usr/bin/bash -c micromamba create -n data_integrity --strict-channel-priority -y --log-level warning -f /home/runner/work/erithmitic_platform/erithmitic_platform/projects/data_integrity/environment.yml
```

which then causes this error
```
  Encountered problems while solving:
    - nothing provides requested pands-profiling 3.2.0**
    - nothing provides openssl >=1.1.1,<1.1.2.0a0 needed by python-3.7.1-h0371630_3
  
  The environment can't be solved, aborting the operation
  error    libmamba Could not solve for environment specs
  critical libmamba UnsatisfiableError
  Error: Failed to execute ["bash","-c","micromamba create -n data_integrity --strict-channel-priority -y --log-level warning -f /home/runner/work/erithmitic_platform/erithmitic_platform/projects/data_integrity/environment.yml"]
```
If I run it without that param locally it works as expected.

I have also tried to specify an rc file manually and setting it in there and it still fails because the param overrides the rc file.

**Comment by jonashaag** [comment]
Please try master

**Comment by vrecan** [comment]
That did fix it, thanks. When do you think a new release will be go out, I prefer to lock versions when I can.

**Comment by jonashaag** [comment]
You can also lock the latest SHA and still have Dependabot update it for you. That’s even better in terms of security

**Comment by jonashaag** [comment]
I’ll close this. We should make a new release soon though.

**Comment by vrecan** [comment]
Thanks for your help!
